name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t msahrha/docker-poetry:latest .
          docker tag msahrha/docker-poetry:latest msahrha/docker-poetry:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push msahrha/docker-poetry:latest
          docker push msahrha/docker-poetry:${{ github.sha }}
